:ems:
  :ems_proxmox:
    :blacklisted_event_names: []
:ems_refresh:
  :proxmox:
    :refresh_interval: 15.minutes
:http_proxy:
  :proxmox:
    :host:
    :password:
    :port:
    :user:
:log:
  :level_proxmox: info
:workers:
  :worker_base:
    :event_catcher:
      :event_catcher_proxmox:
        :poll: 20.seconds
    :queue_worker_base:
      :ems_refresh_worker:
        :ems_refresh_worker_proxmox: {}
